config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :users do
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
    member do
      get 'change_password'
      post 'update_password'
    end
  end
  resources :projects do
    resources :projects_users, shallow: true
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
  end
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :departments do
    resources :comments, shallow: true
    resources :projects_departments, shallow: true
  end
  resources :teams do
    resources :users_teams, shallow: true
    resources :comments, shallow: true
    collection do
      get 'search'
    end
  end
  resources :tasks do
    resources :time_logs, shallow: true
    resources :comments, shallow: true
    resources :tasks_watchers, shallow:true
    resources :attachments, shallow: true
  end
  resources :company_settings
  resources :working_days
  resources :holidays

  get 'reports/tasks'
  get 'reports/time_logs'
  get 'reports/task_audits'
  get 'reports/attendance_report'
  post 'attendance/log_in'
  post 'attendance/log_out'
  post 'tasks/search'
  post 'projects/search_kick'
  post 'users/search_kick'
  post 'teams/search_kick'
  post 'departments/search'
  post 'events/search'

  get 'user_companies/find', controller: 'user_companies', action: 'find'
  post 'user_companies/find', controller: 'user_companies', action: 'search_by_email'
  get 'user_companies/index', controller: 'user_companies', action: 'index'
  get 'dashboard', controller: 'home', action: 'index'
  root to: 'guest#index'
end

app/models/holiday.rb
# frozen_string_literal: true

# Holiday model
class Holiday < ApplicationRecord
  belongs_to :company

  validates :day, presence: true
end

app/controllers/holidays_controller.rb
# frozen_string_literal: true

# Holiday Controller
class HolidaysController < ApplicationController
  load_and_authorize_resource

  def new
    respond_to do |format|
      format.js
    end
  end

  def create
    if @holiday.save
      @holidays = Current.company.holidays
      flash[:notice] = t 'holiday.created'
    else
      flash[:error] = @holiday.errors.full_messages
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @holiday.update(holiday_params)
      @holidays = Current.company.holidays
      flash[:notice] = t 'holiday.updated'
    else
      flash[:error] = @holiday.errors.full_messages
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @holiday.destroy
      @holidays = Current.company.holidays
      flash[:notice] = t 'holiday.destroyed'
    else
      flash[:error] = @holiday.errors.full_messages
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def holiday_params
    params.require(:holiday).permit(:day, :every_year)
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
  def holiday_day(holiday)
    if holiday.every_year?
      holiday.day.strftime("%B, %d")
    else
      holiday.day.to_s(:long)
    end
  end
end

app/views/holidays/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  
    <!-- Modal Header -->
    <div class="modal-header">
      <% if holiday.persisted? %>
        <h4 class="modal-title">Edit Holiday</h4>
      <% else %>
        <h4 class="modal-title">Add Holiday</h4>
      <% end %>
      
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    
    <!-- Modal body -->
    <div class="modal-body">
      <div id="modal-flash-messages"></div>
      <%= form_for holiday, remote: true do |form| %>
        
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group form-check">
                <%= form.check_box :every_year, class: 'form-check-input' %>
                <%= form.label :every_year, class: 'form-check-label' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <%= form.label :day %>
                <%= form.date_field :day, required: true, class: 'form-control' %>
              </div>
            </div>
          </div>

          <%= form.submit class: 'btn btn-dark' %>

        </div>

      <% end %>
    </div>
    
  </div>
</div>

app/views/holidays/_holidays.html.erb
<div class="clearfix"></div>
<span class="h2 mt-4">Holidays</span>
<%= link_to 'Add Holiday', new_holiday_path, remote: true, class: 'btn btn-dark float-right' %>
<table id="working_days_table" class="mt-2 mb-5 table table-hover">
  <thead>
  <tr>
    <th>Date</th>
    <th>Every Year</th>
    <% if can? :update, holidays.first %>
      <th>Action</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  
  <% holidays.each do |holiday| %>
    <tr>
      <td><%= holiday_day(holiday) %> </td>
      <td><%= boolean_value(holiday.every_year?) %> </td>
      <td>
        <% if can? :update, holiday %>
          <%= link_to 'Edit', edit_holiday_path(holiday), remote: true, class: 'btn btn-dark btn-sm' %>
        <% end %>
        <% if can? :destroy, holiday %>
          <%= link_to 'Delete', holiday_path(holiday), remote: true, method: :delete, data: { confirm: 'Are you sure you want to delete?'}, class: 'btn btn-dark btn-sm' %> 
        <% end %>
      </td>
    </tr>        
  <% end %>   
  </tbody>
</table>

app/views/holidays/create.js.erb
<% if flash.now[:error].blank? %>
  $("#holiday-modal").modal('hide');
  $("#flash_messages").html("<%= j render partial: 'shared/flash' %>");
  $("#holidays").html("<%= j render(partial: 'holidays/holidays', locals: { holidays: @holidays }) %>");
<% else %>
  $("#modal-flash-messages").html("<%= j render partial: 'shared/flash' %>");
<% end %>

app/views/holidays/destroy.js.erb
<% if flash.now[:error].blank? %>
  $("#holidays").html("<%= j render(partial: 'holidays/holidays', locals: { holidays: @holidays }) %>");
<% end %>
$("#flash_messages").html("<%= j render partial: 'shared/flash' %>");

app/views/holidays/edit.js.erb
$("#holiday-modal").html("<%= j render partial: 'form', locals: { holiday: @holiday } %>");
$("#holiday-modal").modal('show');

app/views/holidays/new.js.erb
$("#holiday-modal").html("<%= j render partial: 'form', locals: { holiday: @holiday } %>");
$("#holiday-modal").modal('show');

app/views/holidays/update.js.erb
<% if flash.now[:error].blank? %>
  $("#holiday-modal").modal('hide');
  $("#flash_messages").html("<%= j render partial: 'shared/flash' %>");
  $("#holidays").html("<%= j render(partial: 'holidays/holidays', locals: { holidays: @holidays }) %>");
<% else %>
  $("#modal-flash-messages").html("<%= j render partial: 'shared/flash' %>");
<% end %>