config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :users do
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
    member do
      get 'change_password'
      post 'update_password'
    end
  end
  resources :projects do
    resources :projects_users, shallow: true
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
  end
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :departments do
    resources :comments, shallow: true
    resources :projects_departments, shallow: true
  end
  resources :teams do
    resources :users_teams, shallow: true
    resources :comments, shallow: true
    collection do
      get 'search'
    end
  end
  resources :tasks do
    resources :time_logs, shallow: true
    resources :comments, shallow: true
    resources :tasks_watchers, shallow:true
    resources :attachments, shallow: true
  end
  resources :company_settings
  resources :working_days
  resources :holidays

  get 'reports/tasks'
  get 'reports/time_logs'
  get 'reports/task_audits'
  get 'reports/attendance_report'
  post 'attendance/log_in'
  post 'attendance/log_out'
  post 'tasks/search'
  post 'projects/search_kick'
  post 'users/search_kick'
  post 'teams/search_kick'
  post 'departments/search'
  post 'events/search'

  get 'user_companies/find', controller: 'user_companies', action: 'find'
  post 'user_companies/find', controller: 'user_companies', action: 'search_by_email'
  get 'user_companies/index', controller: 'user_companies', action: 'index'
  get 'dashboard', controller: 'home', action: 'index'
  root to: 'guest#index'
end

app/models/task.rb
# frozen_string_literal: true

# Task model
class Task < ApplicationRecord
  audited
  searchkick word_start: [:title, :description]

  STATUS = { 'New' => 'new', 'Pending' => 'pending', 'In Progress' => 'in_progress', 'Completed' => 'completed', 'Closed' => 'closed' }.freeze
  PRIORITY = { low: 1, medium: 2, high: 3 }.freeze
  sequenceid :company, :tasks
  belongs_to :company
  belongs_to :project
  belongs_to :reviewer, class_name: 'User', optional: true
  belongs_to :assignee, class_name: 'User', optional: true
  belongs_to :created_by, class_name: 'User'
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :time_logs, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :tasks_watchers, dependent: :destroy
  has_many :watcher_users, through: :tasks_watchers, source: :watcher, source_type: 'User'
  has_many :watcher_teams, through: :tasks_watchers, source: :watcher, source_type: 'Team'
  has_many :childs, foreign_key: 'parent_id', class_name: 'Task'
  belongs_to :parent, class_name: 'Task', optional: true

  validates :title, presence: true, length: { minimum: 3 }
  validate :validate_end_date
  validate :validate_expected_end_date

  after_update :notify_users

  def validate_end_date
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, I18n.t('task.invalid_end_date'))
    end
  end

  def validate_expected_end_date
    if expected_end_date.present? && expected_start_date.present? && expected_end_date < expected_start_date
      errors.add(:expected_end_date, I18n.t('task.invalid_expected_end_date'))
    end
  end

  def validate_due_date
    if due_date.present? && start_date.present? && due_date < start_date
      errors.add(:due_date, I18n.t('task.invalid_due_date'))
    end
  end

  def notify_users
    user_ids = []
    user_ids << created_by_id
    user_ids << assignee_id
    user_ids << reviewer_id
    user_ids += watcher_users.ids
    user_ids += watcher_teams.map { |team| team.users.ids }.flatten
    user_ids.uniq!
    user_ids.compact!
    user_ids.each do |user_id|
      next unless ProjectsUser.where(project_id: project_id, user_id: user_id).any?

      TaskMailer.delay.notify(user_id, id, company_id)
    end
  end

  def project_name
    project.name
  end

  def assignee_name
    assignee&.full_name
  end

  def reviewer_name
    reviewer&.full_name
  end

  def priority_text
    PRIORITY.key priority
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# Task Controller
class TasksController < ApplicationController
  include TaskFilters

  load_and_authorize_resource find_by: :sequence_num

  # GET /tasks
  def index
    add_breadcrumb 'Tasks', tasks_path

    @tasks = apply_filters(@tasks, params)
    @tasks = @tasks.page(params[:page]).per_page(PER_PAGE)
    @users = User.accessible_by(current_ability)
    @projects = Project.accessible_by(current_ability)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /tasks/:id
  def show
    add_breadcrumb 'Tasks', tasks_path
    add_breadcrumb @task.title, task_path(@task)

    respond_to do |format|
      format.html
    end
  end

  # GET /tasks/new
  def new
    add_breadcrumb 'Tasks', tasks_path
    add_breadcrumb 'Create Task', new_task_path

    @users = User.accessible_by(current_ability)
    @projects = Project.accessible_by(current_ability)
    @task.project_id = params[:project_id] if params[:project_id].present?
    respond_to do |format|
      format.html
    end
  end

  # GET /tasks/:id/edit
  def edit
    add_breadcrumb 'Tasks', tasks_path
    add_breadcrumb @task.title, task_path(@task)
    add_breadcrumb 'Update', edit_task_path

    @users = User.accessible_by(current_ability)
    @projects = Project.accessible_by(current_ability)
    respond_to do |format|
      format.html
    end
  end

  # POST /tasks
  def create
    @task.created_by_id = current_user.id
    if @task.save
      flash[:notice] = t 'task.created'
      redirect_to @task
    else
      errors = @task.errors.full_messages
      flash[:error] = errors
      @users = User.accessible_by(current_ability)
      @projects = Project.accessible_by(current_ability)
      render :new
    end
    respond_to do |format|
      format.html
    end
  end

  # PUT /tasks/:id
  def update
    if @task.update(task_params)
      flash[:notice] = t 'task.updated'
      redirect_to @task
    else
      errors = @task.errors.full_messages
      flash[:error] = errors
      @users = User.accessible_by(current_ability)
      @projects = Project.accessible_by(current_ability)
      render :edit
    end
    respond_to do |format|
      format.html
    end
  end

  # DELETE /tasks/:id
  def destroy
    if @task.destroy
      flash[:notice] = t 'task.destroyed'
      redirect_to tasks_url
    else
      flash[:notice] = t 'task.not_destroyed'
    end
    respond_to do |format|
      format.html
    end
  end

  def search
    @tasks = Task.search(params[:search], match: :word_start)
    respond_to do |format|
      format.js { render 'index' }
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :start_date, :end_date,
                                 :due_date, :expected_start_date, :expected_end_date,
                                 :priority, :status, :assignee_id, :reviewer_id,
                                 :progress, :project_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def watch_button task
    if (task.watcher_users.ids.include?(current_user.id))
      button_to 'Unwatch', tasks_watcher_path(current_user.tasks_watchers.find_by(task_id: task.id)), class: 'ml-3 btn btn-dark', method: :delete, remote: true
    else
      button_to 'Watch', task_tasks_watchers_path(task, { tasks_watcher: { watcher_id: current_user.id, watcher_type: 'User' }}), class: 'ml-3 btn btn-dark', method: :post, remote: true
    end
  end

end

app/views/tasks/_form.html.erb
<%= javascript_pack_tag 'task' %>

<% content_for :card_header do %>
  <% if task.new_record? %>
    <h2 class="card-header font-weight-bold"><%= t(:task_create) %></h2>
  <% else %>
    <h2 class="card-header font-weight-bold"><%= t(:task_update) %></h2>
  <% end %>
<% end %>

<%= form_for task do |form| %>
  <div class="col-lg-12">
    <div class="form-group">
      <%= form.label t(:task_title) %>
      <%= form.text_field :title, class: 'form-control border-info', required: true, minlength: 3 %>
    </div>
  </div>

  <div class="col-lg-12 form-group">
      <%= form.label t(:task_description) %>
      <%= form.text_area :description, class: 'form-control border-info', rows: 5 %>
  </div>

  <div class="row pl-1 pr-1">
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_start_date) %>
      <%= form.date_field :start_date, class: 'form-control border-info' %>
    </div>
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_end_date) %>
      <%= form.date_field :end_date, class: 'form-control border-info' %>
    </div>
  </div>

  <div class="row pl-1 pr-1">
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_expected_start_date) %>
      <%= form.date_field :expected_start_date, class: 'form-control border-info' %>
    </div>

    <div class="col-lg-6 form-group">
      <%= form.label t(:task_expected_end_date) %>
      <%= form.date_field :expected_end_date, class: 'form-control border-info' %>
    </div>
  </div>

  <div class="row  pl-1 pr-1">
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_due_date) %>
      <%= form.date_field :due_date, class: 'form-control border-info' %>
    </div>

    <div class="col-lg-6 form-group">
      <%= form.label t(:task_progress) %>
      <%= form.number_field :progress, in: 0..100, :step => '1', class: 'form-control border-info'%>
    </div>
  </div>

  <div class="row  pl-1 pr-1">
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_priority) %>
      <%= form.select :priority, options_for_select(Task::PRIORITY, task.priority), {}, class: 'form-control border-info' %>
    </div>

    <div class="col-lg-6 form-group">
      <%= form.label t(:task_status) %>
      <%= form.select :status, options_for_select(Task::STATUS, task.status), {}, class: 'form-control border-info' %>
    </div>
  </div>
  
  <div class="row pl-1 pr-1">
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_assignee_id) %>
      <%= form.text_field :assignee_id, data: { pre: { id: task.assignee_id, name: task.assignee&.full_name }.to_json }, class: 'form-control border-info' %>
    </div>

    <div class="col-lg-6 form-group">
      <%= form.label t(:task_project_id) %>
      <%= form.select :project_id, options_from_collection_for_select(@projects, 'id', 'name', task.project_id), {}, {class: "form-control border-info"} %>
    </div>
  </div>

  <div class="row pl-1 pr-1">
    <div class="col-lg-6 form-group">
      <%= form.label t(:task_reviewer_id) %>
      <%= form.text_field :reviewer_id, data: { pre: { id: task.reviewer_id, name: task.reviewer&.full_name }.to_json }, class: 'form-control border-info' %>
    </div>
  </div>
  
  <%= form.submit class: 'btn btn-dark float-right mt-3' %>
  <%= link_to 'Back', :back, class: 'btn btn-dark float-right mr-3 mt-3' %>
<% end %>

app/views/tasks/_new_edit.html.erb
<%= form_for @task do |form| %>
  
  <div class="container-fluid">
    

    <div class="row">
      <div class="col-lg-12">
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control', required: true, minlength: 3 %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">  
        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control', rows: 5 %>
        </div>
      </div>
    </div>

    <div class="row">  
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :start_date %>
          <%= form.date_field :start_date, class: 'form-control' %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :end_date %>
          <%= form.date_field :end_date, class: 'form-control' %>
        </div>
      
      </div>
    </div>

    <div class="row">  
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :expected_start_date %>
          <%= form.date_field :expected_start_date, class: 'form-control' %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :expected_end_date %>
          <%= form.date_field :expected_end_date, class: 'form-control' %>
        </div>

      </div>
    </div>

    <div class="row">  
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :due_date %>
          <%= form.date_field :due_date, class: 'form-control' %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :progress %>
          <%= form.number_field :progress, in: 0..100, :step => '1', class: 'form-control'%>
        </div>
      </div>
    </div>

    <div class="row">
      
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :priority %>
          <%= form.select :priority, options_for_select(Task::PRIORITY), {}, class: 'form-control' %>
        </div>
      </div>
  
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :status %>
          <%= form.select :status, options_for_select(Task::STATUS), {}, class: 'form-control' %>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :assignable_id %>
          <%= form.select :assignable_id, options_for_select( @users.collect{ |u| [u.first_name,u.id] }), {}, {class: "form-control"} %>
        </div>
      </div>
    </div>
    
    <%= link_to 'Back', tasks_path, class: 'btn btn-dark' %>
    <%= form.submit class: 'btn btn-dark' %>

  </div>

<% end %>

app/views/tasks/_table.html.erb
<table id="<%= local_assigns[:table_id] || 'tasks-datatable' %>" data-turbolinks="false" class="table table-hover">
  <thead>
  <tr>
    <th><%= t(:task_title) %></th>
    <th><%= t(:task_project_title) %></th>
    <th><%= t(:task_assignee) %></th>
    <th><%= t(:task_created_by) %></th>
    <th><%= t(:task_status) %></th>
    <th><%= t(:task_priority) %></th>
    <th><%= t(:task_created) %></th>
  </tr>
  </thead>
  <tbody>
  
  <% tasks.each do |task| %>
    <tr>
      <td><%= link_to task.title, task_path(task) %> </td>
      <td> <%= link_to task.project.name, project_path(task.project) %> </td>
      <td> <%= link_to task.assignee.full_name, user_path(task.assignee) if task.assignee %> </td>
      <td> <%= link_to task.created_by.full_name, user_path(task.created_by) %> </td>
      <td> <%= task.status %> </td>
      <td> <%= Task::PRIORITY.key task.priority %> </td>
      <td> <%= task.created_at&.to_s(:long) %> </td>
    </tr>        
  <% end %>
   
  </tbody>
</table>

<% if local_assigns[:paginate] %>
  <div class="digg_pagination">
    <% if request.format.html? %>
      <%= will_paginate @tasks %>
    <% else %>
      <%= js_will_paginate @tasks %>
    <% end %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render partial: "form",locals: {task: @task} %>

app/views/tasks/index.html.erb
<%= javascript_pack_tag 'task' %>

<% content_for :card_header do %>
    <div class="card-header">
      <h2 class="font-weight-bold float-left">Tasks</h2>
      <% if can? :create, Task %>
        <%= button_to "Create Task", new_task_path, method: 'get', class: "btn btn-dark float-right mt-1" %>
      <% end %>
    </div>
<% end %>

<div class="row">      
  <div class="col-lg-6">
    <div class="form-group">
      <%= form_with url: tasks_search_path, remote: true do |f| %>
          <%= f.text_field :search, autofocus: true, class: 'form-control border-info', required: true %>
    </div>
  </div>
  <div class="col-lg-1">
    <div class="form-group">
      <%= f.submit 'Search', class: 'btn btn-dark mr-5 float-right' %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">      
  <div class="col-lg-3">
    <div class="form-group">
      <%= label_tag t(:task_project_id) %>
      <%= select_tag t(:task_project_filter), options_for_select( @projects.collect{ |p| [p.name,p.id] }.unshift(['All',''])), { class: "form-control data-filter" }  %>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="form-group">
      <%= label_tag t(:task_priority) %>
      <%= select_tag :priority, options_for_select(Task::PRIORITY.merge('All'=>'').reverse_each()), class: "form-control data-filter"  %>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="form-group">
      <%= label_tag t(:task_status) %>
      <%= select_tag :status, options_for_select(Task::STATUS.merge('All'=>'').reverse_each()), {class: "form-control data-filter"} %>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="form-group">
      <%= label_tag t(:task_assignee) %>
      <%= select_tag :assignee, options_for_select( @users.collect{ |u| [u.first_name,u.id] }.unshift(['All',''])), {class: "form-control data-filter"} %>
    </div>
  </div>
</div>

<div class="table-responsive my-4" id="tasks-table-div">
  <%= render partial: "table", locals: { paginate: true, tasks: @tasks } %>
</div>  

app/views/tasks/index.js.erb
$("#tasks-table-div").html("<%= j render(partial: 'table', locals: { paginate: true, tasks: @tasks }) %>");
$('#tasks-datatable').DataTable({
    info: false,
    paging: false,
    searching: false
  });

app/views/tasks/new.html.erb
<%= render partial: "form", locals: {task: @task} %>

app/views/tasks/show.html.erb
<%= javascript_pack_tag 'comment', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'time_log', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'report', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'attachment', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'tasks_watchers' %>

<div class="modal" id="tasks-watchers-modal"></div>

<% content_for :card_header do %>
  <div class="card-header">
    <h2 class="font-weight-bold float-left">
      <%= @task.title %>
    </h2>
    <div class="btn-group float-right pt-1" role="group">
      <% if can? :destroy, @task %>
        <%= button_to 'Delete', task_path(@task), class: 'ml-3 btn btn-dark',
        method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
      <% end %>
      <% if can? :update, @task %>
        <%= button_to 'Update', edit_task_path(@task.sequence_num), { class: 'ml-3 btn btn-dark', method: 'get' } %>
      <% end %>

      <div id="watch-button">
        <%= watch_button(@task) %>
      </div>

      <% if can? :create, TasksWatcher %>
        <%= link_to t('task_add_watcher'), new_task_tasks_watcher_path(@task), class: 'ml-3 btn btn-dark', remote: true %>
      <% end %>
      <% if can? :create, TimeLog %>
      
        <%= button_to 'Log Time', new_task_time_log_path(@task), method: 'get', action: 'new', class: 'ml-3 btn btn-dark', remote: true %>
      <% end %>
    </div>
  </div>
<% end %>

<% presenter = TaskPresenter.new(@task) %>

<table class="table">
  <tbody>
    <tr>
      <th><%= t(:task_title) %></th>
      <td><%= @task.title %></td>
    </tr>
    <tr>
      <th><%= t(:task_description) %></th>
      <td><%= @task.description %></td>
    </tr>
    <tr>
      <th><%= t(:task_status) %></th>
      <td><%= @task.status %></td>
    </tr>
    <tr>
      <th><%= t(:task_priority) %></th>
      <td><%= presenter.priority %></td>
    </tr>
    <tr>
      <th><%= t(:task_progress) %></th>
      <td><%= presenter.progress %></td>
    </tr>
    <tr>
      <th><%= t(:task_created_by) %></th>
      <td><%= @task.created_by.full_name %></td>
    </tr>
    <tr>
      <th><%= t(:task_assignee) %></th>
      <td><%= @task.assignee&.full_name %></td>
    </tr>
    <tr>
      <th><%= t(:task_reviewer_id) %></th>
      <td><%= @task.reviewer&.full_name %></td>
    </tr>
    <tr>
      <th><%= t(:task_project_id) %></th>
      <td><%= @task.project.name %></td>
    </tr>
    <tr>
      <th><%= t(:task_start_date) %></th>
      <td><%= @task.start_date&.to_s(:long) %></td>
    </tr>
    <tr>
      <th><%= t(:task_end_date) %></th>
      <td><%= @task.end_date&.to_s(:long) %></td>
    </tr>
    <tr>
      <th><%= t(:task_expected_start_date) %></th>
      <td><%= @task.expected_start_date&.to_s(:long) %></td>
    </tr>
    <tr>
      <th><%= t(:task_expected_end_date) %></th>
      <td><%= @task.expected_end_date&.to_s(:long) %></td>
    </tr>

  </tbody>
</table>
<div class="modal" id="time-log-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Time Logging</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body" id="time-log-modal-body">
        <div id="modal-flash-messages"></div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="attachment-modal" role="dialog"></div>
<%= render partial: 'shared/tabs', locals: { resource: :task } %>