config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :users do
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
    member do
      get 'change_password'
      post 'update_password'
    end
  end
  resources :projects do
    resources :projects_users, shallow: true
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
  end
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :departments do
    resources :comments, shallow: true
    resources :projects_departments, shallow: true
  end
  resources :teams do
    resources :users_teams, shallow: true
    resources :comments, shallow: true
    collection do
      get 'search'
    end
  end
  resources :tasks do
    resources :time_logs, shallow: true
    resources :comments, shallow: true
    resources :tasks_watchers, shallow:true
    resources :attachments, shallow: true
  end
  resources :company_settings
  resources :working_days
  resources :holidays

  get 'reports/tasks'
  get 'reports/time_logs'
  get 'reports/task_audits'
  get 'reports/attendance_report'
  post 'attendance/log_in'
  post 'attendance/log_out'
  post 'tasks/search'
  post 'projects/search_kick'
  post 'users/search_kick'
  post 'teams/search_kick'
  post 'departments/search'
  post 'events/search'

  get 'user_companies/find', controller: 'user_companies', action: 'find'
  post 'user_companies/find', controller: 'user_companies', action: 'search_by_email'
  get 'user_companies/index', controller: 'user_companies', action: 'index'
  get 'dashboard', controller: 'home', action: 'index'
  root to: 'guest#index'
end

app/views/shared/_calendar.html.erb
<%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %>

<div id="event-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="flash-messages"></div>
        <div id="event-form"></div>
      </div>
    </div>
  </div>
</div>
<div class="container w-75 my-4">
  <%= link_to "Add Event", new_event_path, remote: true, class: "btn btn-dark float-right ml-2" %>
  <div id="calendar" data-business-hours="<%= get_business_hours.to_json %>" data-attendances="<%= get_attendances.to_json %>"></div>
  <br />
</div>

app/views/shared/_comments.html.erb
<h2 class="container-fluid w-75 pt-4 pb-2">Leave a comment</h2>
<%= render partial: 'comments/form', locals: { commentable: commentable, comment: comment } %>
</br>
<%= render comments.reverse() %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> d-flex justify-content-between" role="alert">
    <% value = value.first if value.is_a?(Array) && value.length == 1 %>
    <% if value.is_a? Array %>
      <ul>
        <% value.each do |val| %>
          <li><%= val %></li>
        <% end %>
      </ul>
    <% else %>
      <%= value %>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% flash.clear %>

app/views/shared/_sidebar.html.erb
<div id="mySidenav" class="sidenav h-100 pt-5 bg-dark border-right border-secondary">
  <div class="card bg-dark" style="width: 16rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item bg-dark">
        <i class="fa fa-home text-light float-left pt-3" aria-hidden="true"></i>
        <%= link_to "Dashboard", dashboard_path %>
      </li>
      <li class="list-group-item bg-dark">
        <i class="fa fa-list-alt text-light float-left pt-3" aria-hidden="true"></i>
        <%= link_to "Projects", projects_path %>
      </li>
      <li class="list-group-item bg-dark">
        <i class="fa fa-tasks text-light float-left pt-3" aria-hidden="true"></i>
        <%= link_to "Tasks", tasks_path %>
      </li>
      <li class="list-group-item bg-dark">
        <i class="fa fa-users text-light float-left pt-3" aria-hidden="true"></i>
        <%= link_to "Teams", teams_path %>
      </li>
      <% if current_user&.role_id == 1 %>
        <li class="list-group-item bg-dark">
          <i class="fa fa-bar-chart text-light float-left pt-3" aria-hidden="true"></i>
          <a class="dropdown-toggle bg-dark" type="button" data-toggle="dropdown">Reports</a>
            <ul class="dropdown-menu border bg-secondary">
              <li><%= link_to "Tasks", reports_tasks_path, class: 'dropdown-item text-dark' %></li>
              <li><%= link_to "Attendance", reports_attendance_report_path, class: 'dropdown-item text-dark' %></li>
              <li><%= link_to "Time Logs", reports_time_logs_path, class: 'dropdown-item text-dark' %></li>
            </ul>
        </li>
        <li class="list-group-item bg-dark">
          <i class="fa fa-user text-light float-left pt-3" aria-hidden="true"></i>
          <%= link_to "Users", users_path %>
        </li>
        <li class="list-group-item bg-dark">
          <i class="fa fa-user text-light float-left pt-3" aria-hidden="true"></i>
          <%= link_to "Departments", departments_path %>
        </li>
        <li class="list-group-item bg-dark">
          <i class="fa fa-cog text-light float-left pt-3" aria-hidden="true"></i>
          <%= link_to "Settings", company_setting_path(Current.company.company_setting) %>
        </li>
      <% end %>
      <li class="list-group-item bg-dark">
        <i class="fa fa-calendar text-light float-left pt-3" aria-hidden="true"></i>
        <%= link_to "Events", events_path %>
      </li>
    </ul>
  </div>
</div>

<script>
function toggleSidebar() {
  if(document.getElementById("mySidenav").style.width == "250px"){
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("content").style.paddingLeft = "0"
  }
  else{
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("content").style.paddingLeft = "250px"
  }
}
</script>

app/views/shared/_tabs.html.erb
<% tabs = get_resource_tabs(resource) %>
<ul class="nav nav-tabs bg-light rounded-bottom" id="tabs" role="tablist">
  <% tabs.each_with_index do |tab, i| %>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3 <%= 'active' if i.zero? %>" id="<%=tab%>-tab" data-toggle="tab" href="#<%=tab%>-tab-content" data-resource-id='<%= params[:id] %>' role="tab" aria-controls="<%=tab%>-tab-content" aria-selected="true"><%= tab.humanize %>
    </a>
  </li>
  <% end %>
</ul>
<div class="tab-content" id="tabs-content">
  <% tabs.each_with_index do |tab, i| %>
  <div class="tab-pane fade p-4 show <%= 'active' if i.zero? %>" id="<%= tab %>-tab-content" role="tabpanel" aria-labelledby="<%= tab %>-tab">
    <% if tab == 'tasks' %>
      <div id ="tasks-table-div"></div>
    <% end %>
  </div>
  <% end %>
</div>