config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :users do
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
    member do
      get 'change_password'
      post 'update_password'
    end
  end
  resources :projects do
    resources :projects_users, shallow: true
    resources :comments, shallow: true
    resources :attachments, shallow: true
    collection do
      get 'search'
    end
  end
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :departments do
    resources :comments, shallow: true
    resources :projects_departments, shallow: true
  end
  resources :teams do
    resources :users_teams, shallow: true
    resources :comments, shallow: true
    collection do
      get 'search'
    end
  end
  resources :tasks do
    resources :time_logs, shallow: true
    resources :comments, shallow: true
    resources :tasks_watchers, shallow:true
    resources :attachments, shallow: true
  end
  resources :company_settings
  resources :working_days
  resources :holidays

  get 'reports/tasks'
  get 'reports/time_logs'
  get 'reports/task_audits'
  get 'reports/attendance_report'
  post 'attendance/log_in'
  post 'attendance/log_out'
  post 'tasks/search'
  post 'projects/search_kick'
  post 'users/search_kick'
  post 'teams/search_kick'
  post 'departments/search'
  post 'events/search'

  get 'user_companies/find', controller: 'user_companies', action: 'find'
  post 'user_companies/find', controller: 'user_companies', action: 'search_by_email'
  get 'user_companies/index', controller: 'user_companies', action: 'index'
  get 'dashboard', controller: 'home', action: 'index'
  root to: 'guest#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home Controller
class HomeController < ApplicationController
  #Get root
  def index
    @projects = Current.user.projects
    @assigned_tasks = Current.user.assigned_tasks.includes(:project, :assignee, :created_by, :reviewer)
    @watching_tasks = Current.user.watching_tasks.includes(:project, :assignee, :created_by, :reviewer)
    @reviewing_tasks = Current.user.reviewing_tasks.includes(:project, :assignee, :created_by, :reviewer)
    @created_tasks = Current.user.created_tasks.includes(:project, :assignee, :created_by, :reviewer)
    @created_teams = Current.user.created_teams.includes(:created_by, :lead)
    @leading_teams = Current.user.leading_teams.includes(:created_by, :lead)

    @assigned_tasks_piechart_data = @assigned_tasks.group(:status).count
    @watching_tasks_piechart_data = @watching_tasks.group(:status).count
    @created_tasks_piechart_data = @created_tasks.group(:status).count
    @reviewing_tasks_piechart_data = @reviewing_tasks.group(:status).count
    @tasks_timeline_data = Task.accessible_by(current_ability).order(start_date: :asc).pluck(:title, :start_date, :end_date)
    
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div  class="w-100">
    <div class="float-left">
      <% if Current.user.present? %>
        <button class="navbar-toggler float-left mr-2 navbar-toggler-icon p-3 m-1" onclick="toggleSidebar()"></button>
        <%= link_to Current.company.name, dashboard_path, class: 'navbar-brand' %>
      <% else %>
        <%= link_to APP_NAME, root_path, class: 'navbar-brand' %>
      <% end %>
    </div>    
      <% if current_user.nil? %>
        <%= link_to "Sign Up", new_user_registration_path, method: 'get', class: 'btn btn-outline-light my-2 my-sm-0 float-right'%>
        <%= link_to "Log In", user_companies_find_path, method: 'get', class: 'btn btn-outline-light my-2 my-sm-0 float-right mr-3'%>
      <% else %>
        <div class="float-right mr-5">
          <%= get_attendance_button %>
          <div class="nav-item dropdown float-right">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hi, <%=current_user.first_name%>!</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View Profile", user_path(current_user), method: 'get', class: 'dropdown-item'%>
              <div class="dropdown-divider"></div>
              <%= link_to "Change Password", change_password_user_path(Current.user), method: 'get', class: 'dropdown-item'%>
              <div class="dropdown-divider"></div>
              <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: 'dropdown-item'%>
            </div>
          </div>
        </div>  
      <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<%= javascript_pack_tag 'home' %>

<% content_for :card_header do %>
  <div class="card-header h2 font-weight-bold float-left">Dashboard</div>
<% end %>

<% if @tasks_timeline_data.present? %>
  <label class="h4">Tasks Timeline</label>
  <div class='overflow-hidden'><%= timeline @tasks_timeline_data, height: '55vh' %></div>
<% end %>
<%= render partial: "shared/calendar" %>

<ul class="nav nav-tabs bg-light rounded-bottom" id="tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3 active" id="statistics-tab" data-toggle="tab" href="#statistics-tab-content" role="tab" aria-controls="statistics-tab-content" aria-selected="true">Statistics</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="projects-tab" data-toggle="tab" href="#projects-tab-content" role="tab" aria-controls="projects-tab-content" aria-selected="true">My Projects</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="assigned-tasks-tab" data-toggle="tab" href="#assigned-tasks-tab-content" role="tab" aria-controls="assigned-tasks-tab-content" aria-selected="true">Assigned Tasks</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="watching-tasks-tab" data-toggle="tab" href="#watching-tasks-tab-content" role="tab" aria-controls="watching-tasks-tab-content" aria-selected="true">Watching Tasks</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="reviewing-tasks-tab" data-toggle="tab" href="#reviewing-tasks-tab-content" role="tab" aria-controls="reviewing-tasks-tab-content" aria-selected="true">Reviewing Tasks</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="created-tasks-tab" data-toggle="tab" href="#created-tasks-tab-content" role="tab" aria-controls="created-tasks-tab-content" aria-selected="true">Created Tasks</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="created-teams-tab" data-toggle="tab" href="#created-teams-tab-content" role="tab" aria-controls="created-teams-tab-content" aria-selected="true">Created Teams</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link rounded-bottom p-3" id="leading-teams-tab" data-toggle="tab" href="#leading-teams-tab-content" role="tab" aria-controls="leading-teams-tab-content" aria-selected="true">Leading Teams</a>
  </li>
</ul>

<div class="tab-content pt-4" id="tabs-content">
  <div class="tab-pane fade show active" id="statistics-tab-content" role="tabpanel" aria-labelledby="statistics-tab">
    <div class="row text-center">

      <div class="col-lg-3">
        <label class="font-weight-bold">Assigned Tasks</label>
        <%= get_piechart(@assigned_tasks, @assigned_tasks_piechart_data) %>
      </div>
      <div class="col-lg-3">
        <label class="font-weight-bold ">Watching Tasks</label>
        <%= get_piechart(@watching_tasks, @watching_tasks_piechart_data) %>
      </div>
      <div class="col-lg-3">
        <label class="font-weight-bold ">Reviewing Tasks</label>
        <%= get_piechart(@reviewing_tasks, @reviewing_tasks_piechart_data) %>
      </div>
      <div class="col-lg-3">
        <label class="font-weight-bold ">Created Tasks</label>
        <%= get_piechart(@created_tasks, @created_tasks_piechart_data) %>
      </div>
    </div>
  </div>
  <div class="tab-pane fade show" id="projects-tab-content" role="tabpanel" aria-labelledby="projects-tab">
    <%= render partial: 'projects/table', locals: { projects: @projects } %>
    </div>
  <div class="tab-pane fade show" id="assigned-tasks-tab-content" role="tabpanel" aria-labelledby="assigned-tasks-tab">
    <%= render partial: 'tasks/table', locals: { tasks: @assigned_tasks, table_id: 'assigned-tasks-datatable' } %>
  </div>
  <div class="tab-pane fade show" id="watching-tasks-tab-content" role="tabpanel" aria-labelledby="watching-tasks-tab">
    <%= render partial: 'tasks/table', locals: { tasks: @watching_tasks, table_id: 'watching-tasks-datatable' } %>
  </div>
  <div class="tab-pane fade show" id="reviewing-tasks-tab-content" role="tabpanel" aria-labelledby="reviewing-tasks-tab">
    <%= render partial: 'tasks/table', locals: { tasks: @reviewing_tasks, table_id: 'reviewing-tasks-datatable' } %>
  </div>
  <div class="tab-pane fade show" id="created-tasks-tab-content" role="tabpanel" aria-labelledby="created-tasks-tab">
    <%= render partial: 'tasks/table', locals: { tasks: @created_tasks, table_id: 'created-tasks-datatable' } %>
  </div>
  <div class="tab-pane fade show" id="created-teams-tab-content" role="tabpanel" aria-labelledby="created-teams-tab">
    <%= render partial: 'teams/table', locals: { teams: @created_teams, table_id: 'created-teams-datatable' } %>
  </div>
  <div class="tab-pane fade show" id="leading-teams-tab-content" role="tabpanel" aria-labelledby="leading-teams-tab">
    <%= render partial: 'teams/table', locals: { teams: @leading_teams, table_id: 'leading-teams-datatable' } %>
  </div>
</div>